#!/usr/bin/env bash

# Copyright  : (c) 2022-2023 Miao, ZhiCheng
# License    : MIT
# Maintainer : zhicheng.miao@gmail.com
# Synopsis   : Normalize an org file for github wiki to render correctly
# Usage      : normalize-org-file.sh input_file output_file

# The normalization are documented in the code using the notion "a., b., etc."

set -ex

# shellcheck source=/dev/null
source "$(dirname "$0")"/../config.rc

INPUT_FILE=$1
OUTPUT_FILE=$2

INPUT_DIR=$(basename "$(dirname "$INPUT_FILE")")

REM() { cat -; } # Hello BASIC

handle_err() {
    rm -f "$OUTPUT_FILE"
}
trap handle_err ERR

{
    # a. add a notice header.
    cat <<EOF
#+begin_html
<a href="https://www.gnu.org/software/emacs/">
  <img class="badge" src="https://img.shields.io/badge/Made_with-Emacs-nil">
</a>
<a href="https://orgmode.org/">
  <img class="badge" src="https://img.shields.io/badge/Made_with-Org_Mode-nil">
</a>
<a href="https://github.com/yjwen/org-reveal">
  <img class="badge" src="https://img.shields.io/badge/Made_with-ox--reveal.el-nil">
</a>
#+end_html

#+begin_quote
⚠ This file is automatically generated from [[${INPUT_FILE}][this org file]] using
[[https://github.com/hellwolf/github-wiki-utils/blob/master/normalize-org-file.sh][this script]].

The exported presentation can be accessed via [[${GITHACK_URL_BASE}/${INPUT_DIR}/][this githack link]].
#+end_quote

EOF

    # Content Fixups
    cat < "$1" \
        | REM b. fixup paths of file links for rendering on github wiki \
        | sed -e "s|\[\[file:|[[${INPUT_DIR}/|g"  \
        | REM c. rendering babel results text \
        | sed -e "s|^#+RESULTS:|/RESULTS:/\n|ig" \
        | REM d. rendering comments \
        | sed -e "s|^#+begin_comments|#+begin_center|ig" \
              -e "s|^#+end_comments|#+end_center|ig" \
        | REM e. rendering custom revision notes \
        | awk '
          {
            if ($0 ~ /#\+begin_notes :revisions/) {
              print "#+begin_center";
              print "/REVISIONS:/";
              inblock = 1;
            } else if (inblock && $0 ~ /#\+end_notes/) {
              inblock = 0;
              print "#+end_center";
            } else {
              print $0;
            }
          }
' \
        | REM f. remove commented out options \
        | sed -e '/^#+-.*/Id'
} > "$OUTPUT_FILE"
