#!/usr/bin/env bash

# Copyright  : (c) 2022-2023 Miao, ZhiCheng
# License    : MIT
# Maintainer : zhicheng.miao@gmail.com
# Synopsis   : Normalize an org file for github wiki to render correctly
# Usage      : normalize-org-file.sh input_file output_file

# The normalization includes:
# (a) Add a notice header.
# (b) Fixup paths of file links for rendering on github wiki.
# (c) Visualize custom revision notes.

set -ex

source "$(dirname "$0")"/../config.rc

INPUT_FILE=$1
OUTPUT_FILE=$2

INPUT_DIR=$(basename "$(dirname "$INPUT_FILE")")

handle_err() {
    rm -f "$OUTPUT_FILE"
}
trap handle_err ERR

{
    # Notice header (a)
    cat <<EOF
#+begin_html
<a href="https://www.gnu.org/software/emacs/">
  <img class="badge" src="https://img.shields.io/badge/Made_with-Emacs-nil">
</a>
<a href="https://orgmode.org/">
  <img class="badge" src="https://img.shields.io/badge/Made_with-Org_Mode-nil">
</a>
<a href="https://github.com/bastibe/org-static-blog">
  <img class="badge" src="https://img.shields.io/badge/Made_with-org--static--blog-nil">
</a>
#+end_html

#+begin_quote

⚠️This file is automatically generated from [[${INPUT_FILE}][this org file]] using [[https://github.com/hellwolf/github-wiki-utils/blob/master/normalize-org-file.sh][this script]].

The exported presentation can be accessed via [[${GITHACK_URL_BASE}/${INPUT_DIR}/][this githack link]].

#+end_quote

EOF

    # Content Fixups: (b) & (c)
    sed -e "s|\[\[file:|[[${INPUT_DIR}/|g" < "$1" \
    | sed \
        -e "s|^#+begin_comments revisions|#+begin_center|ig" \
        -e "s|^#+end_comments revisions|#+end_center|ig" \
        -e "s|^#+RESULTS:|/RESULTS:/\n|g" \
    | awk '{
        if ($0 ~ /#\+begin_notes :revisions/) {
            print "#+begin_center";
            print "/REVISIONS:/";
            inblock = 1;
        } else if (inblock && $0 ~ /#\+end_notes/) {
            inblock = 0;
            print "#+end_center";
        } else {
            print $0;
        }
    }'
} > "$OUTPUT_FILE"
